image: cimpress.githost.io:4678/docdesign/tools/build_image:latest

stages:
  - build
  - test
  - publish

cache:
  key: "$CI_PIPELINE_ID"
  untracked: true
  paths:
    - artifacts

build:
  tags:
    - docker
  stage: build
  script:
    - dotnet pack --configuration Release --output ../../artifacts src/Cimpress.DataUri/Cimpress.DataUri.csproj /p:PackageVersion=0.0.1

test:
  image: microsoft/dotnet:2.2-sdk
  tags:
    - docker
  stage: test
  script:
    - apt-get update;apt-get install
        libfreeimage3
        libfreetype6 libfontconfig1 -y

    - ln -s /usr/lib/x86_64-linux-gnu/libfreeimage.so.3 /usr/lib/x86_64-linux-gnu/FreeImage.so
    - dotnet test --configuration Release src/Cimpress.DataUri.sln
    
publish:
  tags:
    - docker
  stage: publish
  script:
    - dotnet nuget push ./artifacts/*.nupkg -k $ARTIFACTORY_USERNAME:$ARTIFACTORY_API_KEY -s https://artifactory.cimpress.io/artifactory/api/nuget/nuget-release-local 
  when: manual
  only:
    - master
