image: cimpress.githost.io:4678/docdesign/tools/build_image:latest

stages:
  - build
  - test
  - publish

cache:
  key: "$CI_PIPELINE_ID"
  untracked: true
  paths:
    - artifacts

build:
  tags:
    - docker
  stage: build
  script:
    - dotnet pack --configuration Release --include-symbols --output ../artifacts src/Cimpress.DataUri.sln

test:
  image: microsoft/dotnet:2.2-sdk
  tags:
    - docker
  stage: test
  script:
    - apt-get update
        && apt-get install -y --allow-unauthenticated
            libc6-dev
            libgdiplus
            libx11-dev
        && rm -rf /var/lib/apt/lists/*
    - ln -s /lib64/libdl.so.2 /lib64/libdl.so
    - dotnet test --configuration Release src/Cimpress.DataUri.sln
    
publish:
  tags:
    - docker
  stage: publish
  script:
    - dotnet nuget push ./artifacts/*.nupkg -k $NUGET_ORG_APIKEY
  when: manual
  only:
    - master
